[project]
name = "machine-learning"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupytext>=1.19.5",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "statsmodels>=0.15.0",
]

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.5.260730",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
typeCheckingMode = "basic"
useLibraryCodeForTypes = false

include = [
    "1-linear-regression",
]

exclude = [
    "**/node_modules",
    "**/__pycache__",
    ".venv",
    ".git",
    ".ipynb_checkpoints",
    "**/data",
    "**/models",
]

# analysis = {
#     "diagnosticMode": "openFilesOnly",
#     "autoSearchPaths": true,
# }
